#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

build() {
    set -x
    rm -rf dist
    tsc
    cp -r src/webhive.web/public_html dist/webhive.web
    frontend_test_build
    [ -n "$CI" ] && remove_sources
}

frontend_test_build() {
    set -x
    cd src/webhive.frontend
    rm -rf dist
    npm install --production=false --no-package-lock
    npm run test
    npm run build:prod
    cd ../..
    mkdir -p dist/webhive.frontend
    cp -r src/webhive.frontend/dist dist/webhive.frontend
}

remove_sources() {
    rm -rfv src
}

eslint_run() {
    eslint src --ext ts
}

"$@"
