name: CI
on:
  - push
  - pull_request
jobs:
  build:
    name: 'Test on Node ${{ matrix.node }} and ${{ matrix.os }}'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      - name: 'Setup Node ${{ matrix.node }}'
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: 'Install depependencies'
        run: npm install
      - name: 'Test'
        run: |
          npm run test
