name: 'Harvest'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'
jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Setup Node ${{ matrix.node }}'
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: 'Install depependencies'
        run: npm install
      - name: 'Harvest'
        env:
          API_URL: ${{ secrets.API_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          npm run harvest -- --once
